consul:
  image: progrium/consul
  hostname: node1
  volumes:
  - /container/consul/data:/data
  - /container/consul/consul.json:/config/consul.json
  ports:
  - "10.0.0.1:8300:8300"
  - "10.0.0.1:8301:8301"
  - "10.0.0.1:8301:8301/udp"
  - "10.0.0.1:8302:8302"
  - "10.0.0.1:8302:8302/udp"
  - "10.0.0.1:8400:8400"
  - "10.0.0.1:8500:8500"
  - "53:53/udp"
  command: -server -advertise 10.0.0.1 -bootstrap -ui-dir /ui 
  restart: always
  dns:
  - 10.0.0.1
  - 166.111.8.28
  dns_search: lab.mu
